[package]
name = "astra-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = { workspace = true }
syn = { workspace = true }
quote = { workspace = true }

proc-macro2 = "^1.0.49"
